
server:
  port: 2207
  address: localhost
lavalink:
  server:
    password: ""
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncoding: true
    eventLogs: true
metrics:
  prometheus: false
  endpoint: /metrics
